### PR TITLE
Relax rails dependency

### PR DESCRIPTION
**Pull request by MaximeD**
This relax the rails dependency to allow subversions of rails `6.0` to
use the gem.

In order to simplify the dependencies of the lib, instead of requiring
all rails, just the relevant part are required.

Travis has also been updated to run on rubies 2.5 and 2.6.

### CODE REVIEW

**Comment by chevinbrown** [comment]
> This relax the rails dependency to allow subversions of rails `6.0` to
> use the gem.
> 
> Travis has also be updated to run on rubies 2.5 and 2.6.

Nice ❤️.
Why the manifest changes?

**Comment by MaximeD** [comment]
Thanks :smile:
The manifest was added because it is required by `sprockets` 4, which was updated when I did a new `bundle` after relaxing rails’ dependency.
But not sure that won’t do as latest `sprockets` requires ruby >= 2.5, so that might break for users still using ruby 2.4. I’ll try to see if I can relax the dependency without having `sprockets` upgrading itself :thinking:

**Comment by chevinbrown** [comment]
> Thanks 😄
> The manifest was added because it is required by `sprockets` 4, which was updated when I did a new `bundle` after relaxing rails’ dependency.
> But not sure that won’t do as latest `sprockets` requires ruby >= 2.5, so that might break for users still using ruby 2.4. I’ll try to see if I can relax the dependency without having `sprockets` upgrading itself 🤔

Makes sense! Really, sprockets shouldn't be a dependency...I only passively maintain this gem as an artifact of my last job. 😢 
Either way, I can accept this change if you're not able to keep it slim.

**Comment by MaximeD** [comment]
So in the end, I changed the dependencies to only require the parts of rails that are really needed by this gem. This way no need for `sprockets` anymore!

Let me know :)

**Comment by chevinbrown** [comment]
@MaximeD fantastic!

**Comment by MaximeD** [comment]
Awesome, thank you!

**Pull request merged**
