### PR TITLE
Add state machine

### PR DESCRIPTION
**Pull request by ArmandoMendoza**
Hi @sungwoncho , I added a new generator to create the migrations for update the friendships table. The migration make the change necessary in the data of table.

### CODE REVIEW

**Comment by sungwoncho** [comment]
Thanks for the fix.

* We should probably revert [this line](https://github.com/sungwoncho/has_friendship/blob/master/lib/generators/has_friendship/templates/create_friendships.rb#L6) back to what it was.

* We should generate the new migration file when people run `rails generate has_friendship`. Otherwise new users using 0.1.4 will have to run `rails generate has_friendship` and `rails generate has_friendship_update` to set up the tables. You can add a line after [here](https://github.com/sungwoncho/has_friendship/blob/master/lib/generators/has_friendship/has_friendship_generator.rb#L22).

**Comment by sungwoncho** [comment]
ping @ArmandoMendoza. Just want to see if you have some spare time to implement the fix. Thanks.

**Comment by ArmandoMendoza** [comment]
@sungwoncho sorry for the delay. I was full of work.

**Comment by sungwoncho** [comment]
Thanks. Released as [1.0.0](https://github.com/sungwoncho/has_friendship/blob/master/CHANGELOG.md#100-201657) because people need to run a migration. From now on, I will bump the major version whenever a new migration is added.

**Pull request merged**
