### PR TITLE
Run callbacks on state change

### PR DESCRIPTION
**Pull request by sbadura**
Add ability to create own callbacks.

### CODE REVIEW

**Comment by temkin** [comment]
@sungwoncho could you accept this PR?

**Comment by sungwoncho** [comment]
@temkin sorry for the delay.

This looks useful. @sbadura would you mind adding a test and document it in the README for those wanting to use this feature??

**Comment by sbadura** [comment]
@sungwoncho Done :)

**Comment by sungwoncho** [comment]
Released in [1.1.0](https://github.com/sungwoncho/has_friendship/blob/master/CHANGELOG.md#110-201756). ping @temkin.

Thanks for the PR.

**Comment by temkin** [comment]
@sungwoncho thank you!

**Pull request merged**
