### PR TITLE
Allow Rails 5.2.x

### PR DESCRIPTION
**Pull request by jmajonis**
Rails 5.2 requires minimum Ruby version 2.2.2, however RVM said this version was deprecated and recommended version 2.4.1. 

Rails 5.2 also requires specifying the ActiveRecord::Migration version with lowest possible version 4.2 so I set the minimum required Rails version accordingly.

### CODE REVIEW

**Comment by jforjuly** [comment]
Hey, any updates? Are there any plans to support rails 4.2 ?

**Comment by chevinbrown** [comment]
@sungwoncho it looks like there are plenty of people using this gem and require some amount of involvement to keep it up. 
Are you still interested in being the maintainer?

**Comment by sungwoncho** [comment]
@chevinbrown I cannot maintain this gem at this time because I do not use it personally and do not have bandwidth. Are you interested in maintaining this gem or a fork?

**Comment by chevinbrown** [comment]
I would be happy to share in maintenance and possibly expand the contributor group if you're willing to share. This is a great gem, it just needs a little love.

**Comment by chevinbrown** [comment]
I would be happy to share in maintenance and possibly expand the contributor group if you're willing to share. This is a great gem, it just needs a little love.

❤️

**Comment by chevinbrown** [comment]
@sungwoncho 👀

**Comment by chevinbrown** [comment]
@jmajonis it’s been a bit! Thanks for the contribution!

**Comment by chevinbrown** [comment]
@sungwoncho, how would you like to handle gem updates?

**Comment by chevinbrown** [comment]
@sungwoncho if you're comfortable adding me to the gem owner, I'll prepare a release. 

```
gem owner --add chevinbrown@gmail.com has_friendship
```
I will delete this once you've read it.

**Comment by chevinbrown** [comment]
@sungwoncho are you willing to share gem ownership? If not, I'm not sure I can provide much value to this project since moving forward will require a few frequent releases.

**Pull request merged**
