### PR TITLE
Create unique index migration

### PR DESCRIPTION
**Pull request by xilefff**
Adds concurrently unique index between friendable_id and friend_id to prevent duplicate friendships.

### CODE REVIEW

**Comment by xilefff** [comment]
@chevinbrown what do you think? :)

**Comment by chevinbrown** [comment]
@xilefff looks much better! Will this run if indices exist? My only other concern is that some users of this gem may have added those on their own. `unless index_exists? (:friendable_id, :friend_id)`

**Comment by xilefff** [comment]
My pleasure! Thank you! :)

**Comment by chevinbrown** [comment]
We'll bump the version and release after Thanksgiving.

**Pull request merged**
