### PR TITLE
Allow Rails 5.0.x

### PR DESCRIPTION
**Pull request by adambutler**
This change adds support for Rails 5.0.x. I have been unable to find and breaking changes in my testing.

### CODE REVIEW

**Comment by sungwoncho** [comment]
This is good. But the test is not running.

    `require': cannot load such file -- active_record/railtie (LoadError)

Looking at TravisCI's log, I see that `bundle install` is not installing Rails. Any idea why? I've seen this in https://github.com/sungwoncho/has_friendship/pull/7.

**Comment by adambutler** [comment]
👍  Just taken a look at #7 looks like I just needed to update the gemfile.lock

**Comment by adambutler** [comment]
🌈

**Comment by sungwoncho** [comment]
Released [v1.0.2](https://github.com/sungwoncho/has_friendship/blob/master/CHANGELOG.md#102-2016531).

**Pull request merged**
