### PR TITLE
Stop overriding callback methods if they're present

### PR DESCRIPTION
**Pull request by skycocker**
This PR fixes the case where a callback method (like `on_friendship_created`) is being overridden by an empty method from the template (in removed lines 91-93), if such callback method is defined by e.g. a concern, which is included to the class which uses `has_friendship` as well.

### CODE REVIEW

**Comment by chevinbrown** [comment]
@skycocker 👋 I like this change! 

Would you mind adding a bit of test coverage for the new method?

If you can get that added, I'll be happy to merge & release. ❤️

**Comment by chevinbrown** [comment]
Will this solve the issue here? 
https://github.com/sungwoncho/has_friendship/pull/59

**Comment by skycocker** [comment]
@chevinbrown it will, but it has to be done with caution and after reading the readme notes. I'll provide some tests once I find some spare time :)

**Comment by chevinbrown** [comment]
@skycocker what caution do you mean? 😸 

I can merge this and add a followup PR to add test coverage if that suits you?

**Pull request merged**
